development:
  adapter: postgresql
  encoding: unicode
  database: blog_development
  pool: 5
  username: postgres
  password: kitten8184
  host: localhost
test:
  adapter: postgresql
  encoding: unicode
  database: blog_test
  pool: 5
  username: postgres
  password: kitten8184
  host: localhost
production:
  adapter: postgresql
  encoding: unicode
  database: blog_prod
  pool: 5
  username: postgres
  password: kitten8184
  host: localhost